# Generated by Django 3.2.5 on 2021-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerform',
            name='room_no',
            field=models.IntegerField(null=True),
        ),
    ]
