# Generated by Django 3.2.5 on 2021-07-26 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_customerform_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
