# Generated by Django 3.2.5 on 2021-08-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20210726_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerform',
            name='mobile_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
